### ISSUE TITLE
Access to the path ZipDeployer/temp is denied

### ISSUE THREAD

**Issue by kolte** [haga-rak/Freezer#4]
Hi, 

I was able to get Freezer working in localhost but getting this error on IIS after deploying application. I try to find where this folder is generated so I can give proper read and write access but I don't see this folder being generated anywhere.

Please help.

Thanks,
Girish

**Comment by kolte** [comment]
I figured, folder was created in C:\Windows\System32\config\systemprofile\AppData\Roaming folder, so I had to run the IIS application pool under administrator user. I changed it and worked like charm.

Thanks

**Comment by jnegron357** [comment]
Is there any other way around this error without having to provide administrator privileges to anything?
